#!/usr/bin/env bash

# fix segmentation fault reported in https://github.com/k2-fsa/icefall/issues/674
export PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python

set -eou pipefail

nj=20
stage=3
stop_stage=3
perturb_speed=true

# We assume dl_dir (download dir) contains the following
# directories and files. If not, they will be downloaded
# by this script automatically.
#
#  - $dl_dir/aishell
#      You can find data_aishell, resource_aishell inside it.
#      You can download them from https://www.openslr.org/33
#
#  - $dl_dir/lm
#      This directory contains the language model downloaded from
#        https://huggingface.co/pkufool/aishell_lm
#
#        - 3-gram.unpruned.arpa
#
#  - $dl_dir/musan
#      This directory contains the following directories downloaded from
#       http://www.openslr.org/17/
#
#     - music
#     - noise
#     - speech

dl_dir=$PWD/download

. shared/parse_options.sh || exit 1

# vocab size for sentence piece models.
# It will generate data/lang_bbpe_xxx,
# data/lang_bbpe_yyy if the array contains xxx, yyy

fbank=data/fbank
manifests=data/manifests

vocab_sizes=(
  # 2000
  100
)

# All files generated by this script are saved in "data".
# You can safely remove "data" and rerun this script to regenerate it.
mkdir -p data

log() {
  # This function is from espnet
  local fname=${BASH_SOURCE[1]##*/}
  echo -e "$(date '+%Y-%m-%d %H:%M:%S') (${fname}:${BASH_LINENO[0]}:${FUNCNAME[1]}) $*"
}

log "dl_dir: $dl_dir"

if [ $stage -le 0 ] && [ $stop_stage -ge 0 ]; then
  log "stage 0: Download data"

  # If you have pre-downloaded it to /path/to/aishell,
  # you can create a symlink
  #
  #   ln -sfv /path/to/aishell $dl_dir/aishell
  #
  # The directory structure is
  # aishell/
  # |-- data_aishell
  # |   |-- transcript
  # |   `-- wav
  # `-- resource_aishell
  #     |-- lexicon.txt
  #     `-- speaker.info

  # if [ ! -d $dl_dir/aishell/data_aishell/wav/train ]; then
  #   lhotse download aishell $dl_dir
  # fi

  # If you have pre-downloaded it to /path/to/musan,
  # you can create a symlink
  #
  #   ln -sfv /path/to/musan $dl_dir/musan
  #
  if [ ! -d $dl_dir/musan ]; then
    lhotse download musan $dl_dir
  fi
fi

if [ $stage -le 1 ] && [ $stop_stage -ge 1 ]; then
  log "Stage 1: Prepare Arzen manifest"
  # We assume that you have downloaded the Arzen corpus
  # to $dl_dir/Arzen
  if [ ! -f data/manifests/.Arzen_manifests.done ]; then
    mkdir -p data/manifests
    python /eph/nvme0/ahussein/lhotse/lhotse/recipes/kaldi2lhotseArzen.py 
    touch data/manifests/.Arzen_manifests.done
  fi
fi

if [ $stage -le 2 ] && [ $stop_stage -ge 2 ]; then
  log "Stage 2: Prepare musan manifest"
  # We assume that you have downloaded the musan corpus
  # to data/musan
  if [ ! -f data/manifests/.musan_manifests.done ]; then
    log "It may take 6 minutes"
    mkdir -p data/manifests
    lhotse prepare musan $dl_dir/musan data/manifests
    touch data/manifests/.musan_manifests.done
  fi
fi

if [ $stage -le 3 ] && [ $stop_stage -ge 3 ]; then
  log "Stage 3: Compute fbank for Arzen"
  if [ ! -f data/fbank/.arzen.done ]; then
    mkdir -p $fbank
    ./local/compute_fbank_arzen.py --perturb-speed ${perturb_speed}
    touch data/fbank/.arzen.done
    gunzip -c $fbank/arzen_cuts_train.jsonl.gz | shuf | gzip -c > ${fbank}/arzen_cuts_train_shuf.jsonl.gz
  fi
fi

if [ $stage -le 4 ] && [ $stop_stage -ge 4 ]; then
  log "Stage 4: Compute fbank for musan"
  if [ ! -f data/fbank/.msuan.done ]; then
    mkdir -p data/fbank
    ./local/compute_fbank_musan.py
    touch data/fbank/.msuan.done
  fi
fi


if [ $stage -le 5 ] && [ $stop_stage -ge 5 ]; then
  log "Stage 6: Prepare BPE based lang"
  for vocab_size in ${vocab_sizes[@]}; do
    lang_dir=data/lang_bpe_${vocab_size}
    mkdir -p ${lang_dir}
    if [ ! -f $lang_dir/transcript_words.txt ]; then
      log "Generate text for BPE training from"
      python local/prepare_transcripts.py --cut ${fbank}/arzen_cuts_train_shuf.jsonl.gz --langdir ${lang_dir} 
    fi
    ./local/train_bpe_model.py \
      --lang-dir $lang_dir \
      --vocab-size $vocab_size \
      --transcript $lang_dir/transcript_words.txt 
  done
fi

# whisper large-v3 using 128 mel bins, others using 80 mel bins
whisper_mel_bins=128
output_dir=data/fbank_whisper
if [ $stage -le 30 ] && [ $stop_stage -ge 30 ]; then
  log "Stage 30: Compute ${whisper_mel_bins} dim fbank for whisper model fine-tuning"
  if [ ! -f $output_dir/.arzen.whisper.done ]; then
    mkdir -p $output_dir
    ./local/compute_fbank_arzen.py --perturb-speed ${perturb_speed} --num-mel-bins ${whisper_mel_bins} --whisper-fbank true --output-dir $output_dir
    ./local/compute_fbank_musan.py --num-mel-bins ${whisper_mel_bins} --whisper-fbank true --output-dir $output_dir
    touch $output_dir/.arzen.whisper.done
  fi
fi

whisper_mel_bins=80
output_dir=data/fbank_whisper_small
if [ $stage -le 31 ] && [ $stop_stage -ge 31 ]; then
  log "Stage 30: Compute ${whisper_mel_bins} dim fbank for whisper model fine-tuning"
  if [ ! -f $output_dir/.arzen.whisper.done ]; then
    mkdir -p $output_dir
    ./local/compute_fbank_arzen.py --perturb-speed ${perturb_speed} --num-mel-bins ${whisper_mel_bins} --whisper-fbank true --output-dir $output_dir
    ./local/compute_fbank_musan.py --num-mel-bins ${whisper_mel_bins} --whisper-fbank true --output-dir $output_dir
    touch $output_dir/.arzen.whisper.done
  fi
fi
